export const NAVIGATION_ROUTES = {
    ONBOARDING:'ONBOARDING',
    // AUTH SIDE ROUTES
    SIGN_IN: 'SIGN_IN',
    SIGN_UP: 'SIGN_UP',
    RESETPASSWORD: 'RESETPASSWORD',
    OTPVERIFICATION:'OTPVERIFICATION',
    CREATENEWPASSWORD :'CREATENEWPASSWORD',
    PASSWORDCHANGED :'PASSWORDCHANGED',
    PROFILESCREEN:'PROFILE',
    EDITPROFILE:'EDITPROFILE'

  };